services:
  postgres:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_DB: employees
      POSTGRES_USER: employees
      POSTGRES_PASSWORD: employees
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U employees -d employees'"]
      interval: 3s
      timeout: 2s
      retries: 10

  employees-app:
    image: empapp
    depends_on:
      postgres:
        condition: service_healthy
    expose:
      - 8080
    environment:
      DB_CONNECTION_URL: jdbc:postgresql://postgres:5432/employees
      DB_USERNAME: employees
      DB_PASSWORD: employees
    ports:
      - "8080:8080"