version: '3'

services:
  mysql:
    image: mysql
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: employees
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' # aposztrófok nélkül boolean true-ként értelmezi
      MYSQL_USER: employees
      MYSQL_PASSWORD: employees
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"

  employees-app:
    image: empapp
    depends_on:
      mysql:
        condition: service_healthy
    expose:
      - 8080
    environment:
      DB_CONNECTION_URL: jdbc:mysql://mysql/employees
      DB_USERNAME: employees
      DB_PASSWORD: employees
    ports:
      - "8080:8080"